set_false_path -through [get_nets done_signal/data_cross]
set_false_path -through [get_nets start_signal/data_cross]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 2.5 [current_design]

# cpu reset
set_property PACKAGE_PIN AB7 [get_ports cpu_reset]
set_property IOSTANDARD LVCMOS15 [get_ports cpu_reset]
set_property SLEW SLOW [get_ports cpu_reset]

# system clock
set_property PACKAGE_PIN AD12 [get_ports sysclk_p]
set_property PACKAGE_PIN AD11 [get_ports sysclk_n]
set_property IOSTANDARD LVDS [get_ports sysclk_p]
set_property IOSTANDARD LVDS [get_ports sysclk_n]

# FMC LPC
# ADC clock from FMC150
set_property PACKAGE_PIN AD23 [get_ports clk_ab_p]
set_property PACKAGE_PIN AE24 [get_ports clk_ab_n]
set_property IOSTANDARD LVDS_25 [get_ports clk_ab_p]
set_property IOSTANDARD LVDS_25 [get_ports clk_ab_n]

# common FMC150 signals
set_property PACKAGE_PIN AE28 [get_ports spi_clk]
set_property PACKAGE_PIN AF28 [get_ports spi_mosi]
set_property IOSTANDARD LVCMOS25 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi]

# FMC150 clock signals
set_property PACKAGE_PIN AC29 [get_ports ref_en]
set_property PACKAGE_PIN AC30 [get_ports pll_status]
set_property PACKAGE_PIN AB29 [get_ports cdce_n_en]
set_property PACKAGE_PIN AE29 [get_ports cdce_n_pd]
set_property PACKAGE_PIN AD29 [get_ports cdce_n_reset]
set_property PACKAGE_PIN AB30 [get_ports cdce_miso]
set_property IOSTANDARD LVCMOS25 [get_ports ref_en]
set_property IOSTANDARD LVCMOS25 [get_ports pll_status]
set_property IOSTANDARD LVCMOS25 [get_ports cdce_n_en]
set_property IOSTANDARD LVCMOS25 [get_ports cdce_n_pd]
set_property IOSTANDARD LVCMOS25 [get_ports cdce_n_reset]
set_property IOSTANDARD LVCMOS25 [get_ports cdce_miso]

# FMC ADC signals
set_property PACKAGE_PIN AC22 [get_ports adc_n_en]
set_property PACKAGE_PIN AD24 [get_ports adc_reset]
set_property IOSTANDARD LVCMOS25 [get_ports adc_n_en]
set_property IOSTANDARD LVCMOS25 [get_ports adc_reset]

set_property PACKAGE_PIN AF23 [get_ports {cha_n[0]}]
set_property PACKAGE_PIN AF21 [get_ports {cha_n[1]}]
set_property PACKAGE_PIN AH20 [get_ports {cha_n[2]}]
set_property PACKAGE_PIN AJ21 [get_ports {cha_n[3]}]
set_property PACKAGE_PIN AH22 [get_ports {cha_n[4]}]
set_property PACKAGE_PIN AK21 [get_ports {cha_n[5]}]
set_property PACKAGE_PIN AH25 [get_ports {cha_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {cha_n[6]}]

set_property PACKAGE_PIN AJ23 [get_ports {chb_n[0]}]
set_property PACKAGE_PIN AK24 [get_ports {chb_n[1]}]
set_property PACKAGE_PIN AK25 [get_ports {chb_n[2]}]
set_property PACKAGE_PIN AF25 [get_ports {chb_n[3]}]
set_property PACKAGE_PIN AB20 [get_ports {chb_n[4]}]
set_property PACKAGE_PIN AC25 [get_ports {chb_n[5]}]
set_property PACKAGE_PIN AE21 [get_ports {chb_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {chb_n[6]}]

# FMC DAC signals
set_property PACKAGE_PIN AE30 [get_ports dac_n_en]
set_property PACKAGE_PIN AG28 [get_ports dac_clk_n]
set_property PACKAGE_PIN AK28 [get_ports dac_frame_n]
set_property PACKAGE_PIN AD22 [get_ports dac_tx_en]
set_property IOSTANDARD LVCMOS25 [get_ports dac_n_en]
set_property IOSTANDARD LVDS_25 [get_ports dac_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports dac_frame_n]
set_property IOSTANDARD LVCMOS25 [get_ports dac_tx_en]

set_property PACKAGE_PIN AK30 [get_ports {dac_data_n[0]}]
set_property PACKAGE_PIN AD26 [get_ports {dac_data_n[1]}]
set_property PACKAGE_PIN AH30 [get_ports {dac_data_n[2]}]
set_property PACKAGE_PIN AH27 [get_ports {dac_data_n[3]}]
set_property PACKAGE_PIN AF27 [get_ports {dac_data_n[4]}]
set_property PACKAGE_PIN AK26 [get_ports {dac_data_n[5]}]
set_property PACKAGE_PIN AD28 [get_ports {dac_data_n[6]}]
set_property PACKAGE_PIN AC27 [get_ports {dac_data_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {dac_data_n[7]}]

# FMC monitor signals
set_property PACKAGE_PIN AJ28 [get_ports mon_n_en]
set_property PACKAGE_PIN AJ29 [get_ports mon_n_reset]
set_property PACKAGE_PIN AA30 [get_ports mon_n_int]
set_property IOSTANDARD LVCMOS25 [get_ports mon_n_en]
set_property IOSTANDARD LVCMOS25 [get_ports mon_n_reset]
set_property IOSTANDARD LVCMOS25 [get_ports mon_n_int]

# FMC offset signals
set_property PACKAGE_PIN P23 [get_ports iic_rst]
set_property PACKAGE_PIN K21 [get_ports iic_scl]
set_property PACKAGE_PIN L21 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS25 [get_ports iic_rst]
set_property IOSTANDARD LVCMOS25 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS25 [get_ports iic_sda]

# general io - LEDs
set_property PACKAGE_PIN AB8 [get_ports gpio_led_0]
set_property PACKAGE_PIN AA8 [get_ports gpio_led_1]
set_property PACKAGE_PIN AC9 [get_ports gpio_led_2]
set_property PACKAGE_PIN AB9 [get_ports gpio_led_3]
set_property PACKAGE_PIN AE26 [get_ports gpio_led_4]
set_property PACKAGE_PIN G19 [get_ports gpio_led_5]
set_property PACKAGE_PIN E18 [get_ports gpio_led_6]
set_property PACKAGE_PIN F16 [get_ports gpio_led_7]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_led_0]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_led_1]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_led_2]
set_property IOSTANDARD LVCMOS15 [get_ports gpio_led_3]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_led_4]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_led_5]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_led_6]
set_property IOSTANDARD LVCMOS25 [get_ports gpio_led_7]
